FROM node:16-alpine
# ARG USER_ID
# RUN apt-get -y update

WORKDIR /app

# ユーザーを作成
# ARG USER_ID=1000
# RUN useradd -m -u ${USER_ID} node

# 作成したユーザーに切り替える
# USER node

# ユーザーを作成
# ARG USER_ID=1000
# RUN useradd -m -u ${USER_ID} docker

# 作成したユーザーに切り替える
# USER ${USER_ID}

# RUN ls -al /usr/src/sukebehub-next

# RUN yarn
# RUN yarn build
# RUN yarn next:build
# RUN yarn next:start
